feat: add brankas-income-estimation dashboard
honestbank/grafana-dashboards pull request #106
Opened 2023-04-03 09:55 UTC by xoxwaw

## Pull Request Submission Checklist

Please confirm that you have done the following before requesting reviews:

- [ ] I have confirmed that the PR type is appropriate for the change I am making according to
  the [Honest Pull Request and Commit Message Naming Conventions](https://www.notion.so/honestbank/Pull-Request-and-Commit-Message-Naming-Conventions-bd97f2cbb34c4c73b1ff3a3e384b850c).
- [ ] I have typed an adequate description that explains **why** I am making this change.
- [ ] I have installed and run standard pre-commit hooks that lints and validates my code.

### Description

Add brankas-income-estimation dashboard

2023-04-04 07:41 UTC, wisarootl approved these changes

2023-04-04 07:51 UTC, naveen-pit approved these changes

2023-04-10 07:13 UTC, jai requested changes
UID should reflect workload name

2023-04-10 07:20 UTC, xoxwaw commented
changed the UID to be the same as workload name

2023-04-10 07:41 UTC, jai approved these changes

2023-04-10 07:42 UTC, merged