feat: Create Grafana dashboard for decision engine service
honestbank/grafana-dashboards pull request #49
Opened 2023-01-19 06:32 UTC by kelu-diao

## Pull Request Submission Checklist

Please confirm that you have done the following before requesting reviews:

- [x] I have confirmed that the PR type is appropriate for the change I am making according to
  the [Honest Pull Request and Commit Message Naming Conventions](https://www.notion.so/honestbank/Pull-Request-and-Commit-Message-Naming-Conventions-bd97f2cbb34c4c73b1ff3a3e384b850c).
- [x] I have typed an adequate description that explains **why** I am making this change.
- [x] I have installed and run standard pre-commit hooks that lints and validates my code.

### Description

Add dashboards for the following services at this stage:
- Final decision service
- Allowlist service
- Income features
- Credit feature

Also grouping the backend services by squad

2023-01-19 06:39 UTC, visaruttt requested changes

2023-01-19 06:39 UTC, visaruttt commented on engineering/backend/services/decisioning/feature-engineering-income-service.json
> +          "expr": "rate(database_duration_count{container=\"feature-engineering-income-service\"}[1m])",
I think this service never has a database_duration_count, does this service have a database? how do these metrics come from?

2023-01-19 06:39 UTC, visaruttt commented on engineering/backend/services/decisioning/final-decision-service.json
> +          "expr": "rate(database_duration_count{container=\"final-decision-service\"}[1m])",
I think this service never has a database_duration_count, does this service have a database? how do these metrics come from?

2023-01-19 06:39 UTC, visaruttt commented on engineering/backend/services/decisioning/internal-allowlist-service.json
> +          "expr": "rate(database_duration_count{container=\"internal-allowlist-service\"}[1m])",
I think this service never has a database_duration_count, does this service have a database? how do these metrics come from?

2023-01-19 06:39 UTC, visaruttt commented on engineering/backend/services/self-service/card-management-service.json
> +          "expr": "rate(database_duration_count{container=\"card-management-service\"}[1m])",
this added with your intention? I am not sure how this service works, might need service owner to review this.

2023-01-19 06:41 UTC, bhargavms requested changes

2023-01-19 06:41 UTC, bhargavms commented on engineering/backend/services/decisioning/feature-engineering-credit-service.json
> +          "expr": "rate(database_duration_count{container=\"feature-engineering-credit-service\"}[1m])",
Please change [1m] to `$__rate_interval` variable provided by grafana

usually its best to use `$__rate_interval` instead of hardcoding 1m like this,  because for larger time ranges 1m can be meaningless.

2023-01-19 06:41 UTC, bhargavms commented on engineering/backend/services/decisioning/feature-engineering-credit-service.json
> +          "expr": "rate(field_authorized{container=\"feature-engineering-credit-service\"}[1m])",
same here dont use hardcoded range selectors

2023-01-19 06:41 UTC, kelu-diao commented on engineering/backend/services/decisioning/feature-engineering-income-service.json
> +          "expr": "rate(database_duration_count{container=\"feature-engineering-income-service\"}[1m])",
my bad. Thought I copied from an empty template

2023-01-19 11:03 UTC, visaruttt approved these changes

2023-01-20 06:44 UTC, bhargavms approved these changes

2023-01-20 06:45 UTC, merged